// Code generated by "stringer -type Gender -linecomment"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GenderMale-1]
	_ = x[GenderFemale-2]
}

const _Gender_name = "男女"

var _Gender_index = [...]uint8{0, 3, 6}

func (i Gender) String() string {
	i -= 1
	if i < 0 || i >= Gender(len(_Gender_index)-1) {
		return "Gender(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Gender_name[_Gender_index[i]:_Gender_index[i+1]]
}
